# Generated by Django 4.1.3 on 2023-03-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="biomasse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Localité", models.CharField(max_length=40)),
                ("Localisation", models.CharField(max_length=50)),
                ("Type", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "biomasse",
            },
        ),
    ]
